### ISSUE TITLE
Request: Automatically adjust depending on screen

### ISSUE THREAD

**Issue by spmp** [rubo77/devPixelsPerPx-Toggle#3]
With a dual monitor setup with different DPI's per monitor I need to change the layout.css.devPixelsPerPx when I drag the firefox window from one monitor to the next (i.e laptop to external).
Can you add the ability to automatically adjust layout.css.devPixelsPerPx to the scaling set for the display the firefox window is in?
In Ubuntu the scaling that I set per monitor matches what I set in layout.css.devPixelsPerPx well, i.e 1.62.
Cheers

**Comment by rubo77** [comment]
At the moment i have no time to develop this any further, but fell free to fork this repo and try out to add this functionality. I would accept your pull request if it works

**Comment by bhazelwood** [comment]
If you don't feel like forking, try this https://addons.mozilla.org/En-us/firefox/addon/autohidpi/

(Hope @rubo77 doesn't mind me linking to this)

**Comment by spmp** [comment]
This is _exactly_ what I was looking for.
 Thank you.

**Comment by rubo77** [comment]
Thanks, nice Addon: <a href="https://addons.mozilla.org/En-us/firefox/addon/autohidpi/">AutoHiDPI</a> might be the better solution than my first try here ;-)
