### ISSUE TITLE
Uninstalling should leave the value if it has been modified since installation

### ISSUE THREAD

**Issue by nicolas-raoul** [rubo77/devPixelsPerPx-Toggle#5]
I did the following:
1. Install this add-on
2. Set the css parameter manually to 1.4 as 2 is too big for my screen
3. Forget about the add-on for a long time
4. One day, I decided to uninstall all unnecessary add-ons
5. My css parameter was reset to default (which means an effective value of 1)

So, how about leaving the value as-is if it is not 1 or 2?

**Comment by rubo77** [comment]
I think -1 means default

**Comment by nicolas-raoul** [comment]
Oh I see thanks for the info! I reworded the enhancement request.
Thanks for this add-on which I am sure is useful to tons of people :-)

**Comment by rubo77** [comment]
I think an add-on should always reset all values to default when you uninstall or disable it.

 So leaving a value as it is on uninstall is not an option.

you can set the value as you wish after uninstallation

**Comment by nicolas-raoul** [comment]
Like you want :-)
I close this enhancement request, then.
